import { Nunito, Geist, Geist_Mono } from "next/font/google";
import Image from "next/image";
import Link from "next/link";
import "./globals.css";

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Park Shore Camp & School",
  description: "Generated by KickAds",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${nunito.variable} ${nunito.variable} antialiased`}>
        <header>
            <div className="logo">
              <Link href={"/"}>
              <Image
                        className="psNavIcon"
                        src="/images/nav_imgs/parkShore_nav_Icon.png"
                        alt="Parkshore Light logo"
                        width={256}
                        height={62}
                        style={{width: '256px', height: 'auto'}}
                        priority
                      />
              </Link>
            </div>
            <nav>
                <ul>                                              
                    <li><Link href={"/"}>Home</Link></li>
                    <li><Link href={"/about"}>About</Link></li>             
                    <li><Link href={"/programs"}>Programs</Link></li>    
                    <li><Link href={"/activities"}>Activities</Link></li>    
                    <li><Link href={"/dates"}>Dates</Link></li>    
                    {/* <li><Link href={"/camp"}>Camp</Link></li>
                    <li><Link href={"/school"}>School</Link></li>
                    <li><Link href={"/staff"}>Staff</Link></li> */}
                    <li><Link href={"/contact"}>Contact</Link></li>              
                    <li className="enrollNow"><Link href={"/contact"}>Enroll</Link></li> 
                </ul>
            </nav>
        </header>
        {children}
        <footer>
            <div className="leftFooter">
              <Link href={"/"}>
              <Image
                        className="psFtrIcon"
                        src="/images/nav_imgs/parkShore_ftr_Icon.png"
                        alt="Parkshore Dark logo"
                        width={256}
                        height={62}
                        style={{width: '256px', height: 'auto'}}
                        priority
                      />
              </Link>
              <ul className="campInfo">
                  <li><span className="featureTxt">Visit Us:</span> <a href="https://maps.app.goo.gl/ZpYcXg52bSCFJhLW9" target="_blank" rel="noopener noreferrer">450 Deer Park Road Dix Hills, NY 11746</a></li>
                  <li><span className="featureTxt">Contact Us:</span> <a href="tel:+6314998580">(631) 499-8580</a>| <a href="mailto:info@parkshoredaycamp.com">Info@ParkShoreDayCamp.com</a></li>
                  <li><span className="featureTxt">Learn More About:</span> Park Shore Country Day Camp </li>
                  <li><span className="featureTxt">Learn More About:</span> Park Shore Country School </li>
                  <li><span className="featureTxt">Tours:</span> Call Tricia at park shore to set up a day and time for a personalized tour! </li>
              </ul>
            </div>
            <div className="rightFooter">
              <nav>
                  <ul>                                              
                      <li><Link href={"/"}>Home</Link></li>
                      <li><Link href={"/camp"}>Camp</Link></li>
                      <li><Link href={"/school"}>School</Link></li>
                      <li><Link href={"/staff"}>Staff</Link></li>
                      <li><Link href={"/about"}>About</Link></li>             
                      <li><Link href={"/contact"}>Contact</Link></li>              
                      <li className="enrollNow"><Link href={"/contact"}>Enroll</Link></li>              
                      <li className="Call"><Link href={"tel:+6314998580"}>Call</Link></li>      
                  </ul>
              </nav>
              <ul className="socialMedia">
                <li>
                    <a
                      href="https://www.facebook.com/ParkShoreDayCamp/"
                      target="_blank"
                      rel="noopener noreferrer"
                    >
                      <Image
                        src="/images/social_imgs/social_Img_fb.jpg"
                        alt="Facebook"
                        width={50}
                        height={50}
                      />
                    </a>
                </li>
                <li>
                    <a
                      href="https://www.instagram.com/park_shore_camp_and_school/"
                      target="_blank"
                      rel="noopener noreferrer"
                    >
                      <Image
                        src="/images/social_imgs/social_Img_insta.jpg"
                        alt="Instagram"
                        width={50}
                        height={50}
                      />
                    </a>
                </li>
                <li>
                    <a
                      href="https://www.youtube.com/user/ParkShoreDayCamp/featured"
                      target="_blank"
                      rel="noopener noreferrer"
                    >
                      <Image
                        src="/images/social_imgs/social_Img_yt.jpg"
                        alt="YouTube"
                        width={50}
                        height={50}
                      />
                    </a>
                </li>
              </ul>
            </div>
        


        </footer>        
      </body>
    </html>
  );
}
